console.log(Math.PI.toFixed(3))
console.log(Math.abs(-6))
console.log(Math.round(3.5))
console.log(Math.floor(3.99))
console.log(Math.ceil(3.1))
console.log(Math.trunc(9.11))
console.log(Math.pow(2,3))
console.log(2**3)
console.log(Math.sqrt(144))
console.log(Math.log(8))
console.log(Math.log2(8))

console.log("----------------")
// console.log((Math.random()*100))
// console.log((Math.random()*100).toFixed(0))
console.log(Math.trunc(Math.random()*100))